version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_orm_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - mini_orm_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mini_orm
      - DB_USERNAME=root
      - DB_PASSWORD=root_password

  db:
    image: mysql:8.0
    container_name: mini_orm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mini_orm
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mini_orm_network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mini_orm_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mini_orm_network

volumes:
  mysql_data:

networks:
  mini_orm_network:
    driver: bridge
